networks:
  default:
    external: true
    name: roboshop

services:
  mongodb:
    image: mongodb:5
    networks:
      - roboshop

  catalogue:
    image: catalogue:v1
    networks:
      - roboshop
    depends_on:
      - mongodb

  web:
    image: web:1
    ports:
      - "80:80"
    depends_on:
      - catalogue



